"""Checkpoint identities and training limits; runtime controls live in settings."""

QUESTION_SLICE_MODEL = "mySociety/modernbert-question-slice-v2"
QUESTION_SLICE_REVISION = "eb0436d4be96f113f35b5f891f9cc876a0f0bd6b"
QUESTION_SLICE_INPUT_LIMIT = 768
GRANITE_INPUT_LIMIT = 2048
GRANITE_OUTPUT_LIMIT = 2048
GRANITE_MIN_OUTPUT_TOKENS = 256
GRANITE_OUTPUT_OVERHEAD = 64
GRANITE_OUTPUT_TOKENS_PER_QUESTION = 192
GRANITE_MAX_QUESTIONS = (
    GRANITE_OUTPUT_LIMIT - GRANITE_OUTPUT_OVERHEAD
) // GRANITE_OUTPUT_TOKENS_PER_QUESTION

GRANITE_MERGED = "mySociety/granite-tiny-foi-topic-grounded-v2-merged"
GRANITE_MERGED_REVISION = "c2ba6b86e43977bcb71bc90f12dc0cad42ac7e79"
