name: Push mirror to git.mysociety.org

on:
  push:
  workflow_dispatch:
    inputs:
      force_push:
        description: 'Force push branch'
        type: boolean
        required: false

permissions:
  contents: read

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262  # v4
      with:
        persist-credentials: false
        fetch-depth: '0'

    - name: Push branch to git.mysociety.org
      id: push_to_mirror
      if: ${{ github.event.inputs.force_push == 'false' || !github.event.inputs.force_push }}
      uses: mysociety/action-git-pusher@f14fa9e98fe817016fc9f41d9a530f316df2735b  # v1.3.0
      with:
        git_ssh_key: ${{ secrets.PUBLICCVS_GIT_KEY }}
        ssh_known_hosts: ${{ secrets.GIT_KNOWN_HOSTS }}
        tag: ${{ github.ref_name }}
        remote: 'ssh://gh-public@git.mysociety.org/data/git/public/llm-management.git'


    - name: Push branch to git.mysociety.org (force)
      id: push_to_mirror_force
      if: ${{ github.event.inputs.force_push == 'true' }}
      uses: mysociety/action-git-pusher@f14fa9e98fe817016fc9f41d9a530f316df2735b  # v1.3.0
      with:
        git_ssh_key: ${{ secrets.PUBLICCVS_GIT_KEY }}
        ssh_known_hosts: ${{ secrets.GIT_KNOWN_HOSTS }}
        tag: ${{ github.ref_name }}
        remote: 'ssh://gh-public@git.mysociety.org/data/git/public/llm-management.git'
        extra_git_config: --force
